// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTF_0sPg2v4VkGm-ctBji6hzZ-WHliUis',
    appId: '1:643071460200:web:93f2128cd66d7173b9ccdd',
    messagingSenderId: '643071460200',
    projectId: 'drivo-41f2e',
    authDomain: 'drivo-41f2e.firebaseapp.com',
    storageBucket: 'drivo-41f2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPQa_hpNZ5APrH9Albcm8lx3uHflHzx4',
    appId: '1:643071460200:android:f5d323434205b0d4b9ccdd',
    messagingSenderId: '643071460200',
    projectId: 'drivo-41f2e',
    storageBucket: 'drivo-41f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvgx-R0P0ton_Z9JvpWf8kT_952zqk-B8',
    appId: '1:643071460200:ios:f525a0fc4df37b2bb9ccdd',
    messagingSenderId: '643071460200',
    projectId: 'drivo-41f2e',
    storageBucket: 'drivo-41f2e.firebasestorage.app',
    iosBundleId: 'com.hwiloUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvgx-R0P0ton_Z9JvpWf8kT_952zqk-B8',
    appId: '1:643071460200:ios:d61f39aaee1b6091b9ccdd',
    messagingSenderId: '643071460200',
    projectId: 'drivo-41f2e',
    storageBucket: 'drivo-41f2e.firebasestorage.app',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTF_0sPg2v4VkGm-ctBji6hzZ-WHliUis',
    appId: '1:643071460200:web:721d09eb1212ae23b9ccdd',
    messagingSenderId: '643071460200',
    projectId: 'drivo-41f2e',
    authDomain: 'drivo-41f2e.firebaseapp.com',
    storageBucket: 'drivo-41f2e.firebasestorage.app',
  );

}